### ISSUE TITLE
setUserID dose not accept numbers

### ISSUE THREAD

**Issue by 3alampro** [capacitor-community/firebase-analytics#1]
Hello,

the `setUserID` method does not accept integer as parameter the code give this error

```
To Native ->    
AnalyticsPlugin   
setUserID   
22003479   
ERROR MESSAGE:    
{"errorMessage":"","message":"missing user id value"}   
⚡️  [error] - ERROR Error: Uncaught (in promise): Object: {"errorMessage":"","message":"missing user id value"}
```

in my code all my users id are integers so to work around this issue i needed to convert the returned integer into string so `setUserID` can work without any issue 

can this be improved to accept integers and string as will in the feature it will be great

**Comment by stewones** [comment]
hello there. this is a firebase limitation. we can't set UserID as a number.

although you can easily workaround that by appending a `.toString()`
