### ISSUE TITLE
Crashes on VueJS implementation

### ISSUE THREAD

**Issue by MikeCraig418** [capacitor-community/firebase-analytics#10]
Has anyone had success with VueJS and Capacitor?

I get:

`⚡️  [error] - {"line":1,"column":5502,"sourceURL":"capacitor://localhost/js/app.63a4a7d6.js"}`

in my iOS Console.

**Comment by MikeCraig418** [comment]
Hello! I found my problem. I'm sorry, I needed to run `npx cap update` after installing the plugin.

Could you add this step in the README.md? 

Thanks again!

**Comment by brownoxford** [comment]
README.md has since been updated to include instructions to run `npx cap sync` after installing plugin, closing.
