### ISSUE TITLE
Firebase is not initialized when using on mobile

### ISSUE THREAD

**Issue by carlosen14** [capacitor-community/firebase-analytics#102]
**Describe the bug**
I get it working on Web and can see information on GAnalytics site, but on Android and iOS I only get in console `Firebase analytics is not initialized. Make sure initializeFirebase() is called once`

I have the setup like this.

```ts
  async setup () {
    if (this.platform.is('desktop')) {
     // ionic serve log this
      try {
        console.log('analytics for web')
        const result = await FirebaseAnalytics.initializeFirebase({
          apiKey: 'asdfg',
          authDomain: 'asdf.firebaseapp.com',
          projectId: 'asdf',
          storageBucket: 'asdf.appspot.com',
          messagingSenderId: 'asdf',
          appId: 'asdfg',
          measurementId: 'G-asdf'
        })
        console.log('analytics configured', result)
        await this.setCollectionsEnabled(true)
        this._isConfigured = true
      } catch (err) {
        console.log('analytics configured err', err)
        this._isConfigured = false
      }
    } else if (this.platform.is('mobile')) {
      // Android and iOS log this
      await this.setCollectionsEnabled(true) // I thought this was going to do the initialize, but it doesn't
      console.log('analytics for mobile')
      this._isConfigured = true
    }
    this.setDefaults()
  }
```

The  setup function is called on app.module.ts

But when I try to log something i get the error multiple times, example like this

`    FirebaseAnalytics.logEvent({ name, params })`

**Expected behavior**
To work on Android and iOS

**Screenshots**
Mobile log is called
![image](https://user-images.githubusercontent.com/9368632/126555679-3b560a89-c4ee-4ddf-ba52-672701805984.png)

A few logs later the error appears.
![image](https://user-images.githubusercontent.com/9368632/126555776-22f92b69-2ba4-472e-bccf-a00508d585b6.png)

**Desktop (please complete the following information):**
ionic 6.16.3
capacitor  2.4.6
macbook pro m1 
mac osx 11.3.1
xcode 12.5.1
android studio 4.2.1

  ```json
  "@angular/common": "^10.2.4",
    "@angular/core": "^10.2.4",
    "@angular/forms": "^10.2.4",
    "@angular/platform-browser": "^10.2.4",
    "@angular/platform-browser-dynamic": "^10.2.4",
    "@angular/router": "^10.2.4",
    "@apollo/client": "^3.0.0",
    "@byteowls/capacitor-oauth2": "^2.1.0",
    "@capacitor-community/firebase-analytics": "^0.3.3",
    "@capacitor/android": "^2.4.6",
    "@capacitor/core": "2.4.6",
    "@capacitor/ios": "^2.4.6",
    "@fortawesome/angular-fontawesome": "^0.8.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.34",
    "@fortawesome/free-brands-svg-icons": "^5.15.2",
    "@fortawesome/free-regular-svg-icons": "^5.15.2",
    "@fortawesome/free-solid-svg-icons": "^5.15.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/in-app-browser": "^5.33.1",
    "@ionic-super-tabs/angular": "^7.0.8",
    "@ionic-super-tabs/core": "^7.0.8",
    "@ionic/angular": "^5.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@sentry/capacitor": "^0.1.0",
    "apollo-angular": "^2.2.0",
    "conekta-capacitor": "0.0.22",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "graphql": "^15.0.0",
    "jetifier": "^1.6.6",
    "js-base64": "^3.6.1",
    "leaflet": "^1.7.1",
    "lodash": "^4.17.20",
    "marked": "^2.0.3",
    "moment": "^2.29.1",
    "rxjs": "^6.6.3",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1000.8",
    "@angular/cli": "^10.2.1",
    "@angular/compiler": "^10.2.4",
    "@angular/compiler-cli": "^10.2.4",
    "@angular/language-service": "^10.2.4",
    "@capacitor/cli": "^2.4.6",
    "@compodoc/compodoc": "^1.1.11",
    "@ionic/angular-toolkit": "^2.3.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/leaflet": "^1.5.21",
    "@types/lodash": "^4.14.168",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "^4.10.0",
    "@typescript-eslint/parser": "^4.10.0",
    "codelyzer": "^6.0.0",
    "ionic-version": "^1.0.3",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "nconf": "^0.11.2",
    "netlify": "^6.1.29",
    "protractor": "~7.0.0",
    "snazzy": "^9.0.0",
    "standard": "^16.0.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  },

```

**Smartphone (please complete the following information):**
android 9 (samsung s8+)
iOS 14.6 (iphone xr)

Or is it that i have to use the web configuration for mobile too?

**Comment by carlosen14** [comment]
Also, I got this on Android Studio, despite this it does compile, but may be related
![image](https://user-images.githubusercontent.com/9368632/126573907-93b3deff-30af-4f8b-bb71-c02e9bb3e5e5.png)

**Comment by carlosen14** [comment]
I tested the example app, and I see a difference, the library is not being loaded correctly into the project.
![image](https://user-images.githubusercontent.com/9368632/126686098-ab4060ac-96b3-4108-9384-58967522fe24.png)

**Comment by carlosen14** [comment]
Just found my issue, I was looking the README for capacitor 3, which is in branch master and it says 

```ts
import { FirebaseAnalytics } from "@capacitor-community/firebase-analytics";
```
And this was different for capacitor 2, which I found looking at the README inside node_modules/@capacitor-community/firebase-analytics/README.md.

```ts
import "@capacitor-community/firebase-analytics";
import { Plugins } from "@capacitor/core";
const { FirebaseAnalytics } = Plugins;
```

this does not fix the issue with Android Studio, but at least it is now working and recognizing the user, events, logs and page views.

**Comment by sneko** [comment]
I faced the exact same issue than @carlosen14 for some time , I just read the documentation using directly
```
import { FirebaseAnalytics } from "@capacitor-community/firebase-analytics";
```

whereas I should have used native access
```
const { FirebaseAnalytics } = Plugins;
```

Maybe the doc' should be improved for this? I guess in most case people will use this plugin for native apps.

cc @brownoxford

**Comment by lander854** [comment]
same issue but the answers here are outdated...

**Comment by satya319** [comment]
I am also facing the same issue even after calling the function in my app.component.ts file  for my ionic app.
![image](https://github.com/user-attachments/assets/5f2ac47d-0088-468f-a9c7-c93497b1532a)
