### ISSUE TITLE
Capacitor 3 - Xcode iOS build - "Cannot force unwrap value of non-optional type 'String'" v1.0.0

### ISSUE THREAD

**Issue by nadavhalfon** [capacitor-community/firebase-analytics#105]
**Describe the bug**
When building ionic capacitor 3 app, Xcode gives this error "Cannot force unwrap value of non-optional type 'String'" (line 54, Plugin.swift)

**To Reproduce**
1. Install version 1.0.0 of this lib and make sure you use capacitor 3
2. Sync iOS
3. Build project using Xcode 

**Expected behavior**
Build should pass without compiler error

**Screenshots**
![image](https://user-images.githubusercontent.com/32557985/131248799-16f808b7-ccac-4fa2-874b-14aa68aa3aca.png)

**Desktop (please complete the following information):**
 - OS: Big Sur 11.5.2

**Smartphone (please complete the following information):**
 - Device: iPhone 12 PRO
 - OS: iOS 14.7.1

**Additional context**
For now I actually edited the node modules and erased the ! from that line of code.
I need you help, thank you!

**Comment by f1ght4fun** [comment]
any solution - have the same =/ ??

**Comment by mattsputnikdigital** [comment]
Same here

**Comment by mattsputnikdigital** [comment]
Try running in the iOS folder

```
sudo gem install cocoapods --pre
pod repo update
```

**Comment by alexbonhomme** [comment]
Same issue here :(

**Comment by alexbonhomme** [comment]
Uninstall and reinstall last version seems to fix this issue :

```sh
npm un @capacitor-community/firebase-analytics
npm install @capacitor-community/firebase-analytics@latest
npx cap sync ios
```
