### ISSUE TITLE
Correct Android config for capacitor v3?

### ISSUE THREAD

**Issue by santekotturi** [capacitor-community/firebase-analytics#106]
The docs for this plugin mention that we should be adding this plugin to MainActivity.java. However, the capacitor v3 docs say that most plugins don't need to be imported this way, instead they're automatically imported. 

https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading

Do we need this code block anymore?
```
import com.getcapacitor.community.firebaseanalytics.FirebaseAnalytics;

public class MainActivity extends BridgeActivity {

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(
        savedInstanceState,
        new ArrayList<Class<? extends Plugin>>() {

          {
            // Additional plugins you've installed go here
            // Ex: add(TotallyAwesomePlugin.class);
            add(FirebaseAnalytics.class);
          }
        }
      );
  }
}
```

**Comment by KBRR11** [comment]
If you use capacitor v3 you should change this.init(); to registerPlugin(FirebaseAnalytics.class);

```
public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    registerPlugin(FirebaseAnalytics.class);

  }
}
```

**Comment by wcooperscott** [comment]
On Capacitor 3, after importing
`import com.getcapacitor.community.firebaseanalytics.FirebaseAnalytics;`

I insert:
`registerPlugin(FirebaseAnalytics.class);`
and received the error: Cannot resolve symbol 'FirebaseAnalytics'

Any help on this?

**Comment by eric-horodyski** [comment]
> On Capacitor 3, after importing `import com.getcapacitor.community.firebaseanalytics.FirebaseAnalytics;`
> 
> I insert: `registerPlugin(FirebaseAnalytics.class);` and received the error: Cannot resolve symbol 'FirebaseAnalytics'
> 
> Any help on this?

Try running **File > Sync Project with Gradle Files** within Android Studio to get the imported package recognized.

**Comment by 3preston** [comment]
> > On Capacitor 3, after importing `import com.getcapacitor.community.firebaseanalytics.FirebaseAnalytics;`
> > I insert: `registerPlugin(FirebaseAnalytics.class);` and received the error: Cannot resolve symbol 'FirebaseAnalytics'
> > Any help on this?
> 
> Try running **File > Sync Project with Gradle Files** within Android Studio to get the imported package recognized.

This worked to get the app built and running on android studio, but the analytics dont seem to be firing. Any thoughts/suggestions?

**Comment by SergioZhydecky** [comment]
try also to add 
```
        <key>FIREBASE_ANALYTICS_COLLECTION_ENABLED</key>
	<string>$ANALYTICS_COLLECTION_ENABLED</string>
	<key>FirebaseAutomaticScreenReportingEnabled</key>
	<string>$AUTOMATIC_SCREEN_REPORTING_ENABLED</string>
```

**Comment by selected-pixel-jameson** [comment]
@KBRR11 Could you put this in the documentation please?

**Comment by 3preston** [comment]
> try also to add
> 
> ```
>         <key>FIREBASE_ANALYTICS_COLLECTION_ENABLED</key>
> 	<string>$ANALYTICS_COLLECTION_ENABLED</string>
> 	<key>FirebaseAutomaticScreenReportingEnabled</key>
> 	<string>$AUTOMATIC_SCREEN_REPORTING_ENABLED</string>
> ```

What file would this go into?

**Comment by RodrigoRomero2308** [comment]
> try also to add
> 
> ```
>         <key>FIREBASE_ANALYTICS_COLLECTION_ENABLED</key>
> 	<string>$ANALYTICS_COLLECTION_ENABLED</string>
> 	<key>FirebaseAutomaticScreenReportingEnabled</key>
> 	<string>$AUTOMATIC_SCREEN_REPORTING_ENABLED</string>
> ```

Is that going in the GoogleService plist file for IOS? It seems to have the same format as the keys inside the dict tag

**Comment by brownoxford** [comment]
Updated docs - because of the Capacitor 3's [automatic Android plugin loading](https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading), you no longer need to edit `MainActivity.java` when adding or removing files via NPM.
> In Capacitor 3, it is preferred to automatically load the Android plugins. In MainActivity.java, the onCreate method can be removed. You no longer have to edit this file when adding or removing plugins installed via npm.
