### ISSUE TITLE
SetScreenName on Web

### ISSUE THREAD

**Issue by ghost** [capacitor-community/firebase-analytics#112]
**Is your feature request related to a problem? Please describe.**
I'm wondering why "setScreenName" is not available on Web, since we would love to track everything the same way on Android, iOS and Web. 

**Describe the solution you'd like**
Basically the method "setScreenName" would be required to work on Web, also a potential automatic screen tracking must be disabled. 

**Describe alternatives you've considered**
I'm not sure if there's an alternative.

**Comment by ghost** [comment]
Nevermind, there's actually the possibility to to use the logEvent method with event name "screen_view". See https://firebase.google.com/docs/analytics/screenviews#web-version-8 for reference, just in case somebody else is having the same issue.

**Comment by media4learning** [comment]
> Nevermind, there's actually the possibility to to use the logEvent method with event name "screen_view". See https://firebase.google.com/docs/analytics/screenviews#web-version-8 for reference, just in case somebody else is having the same issue.

Hi, I have the same issue. Logging the screen_view event does work, but the automatic page tracking is still enabled for web an I see no way to disable it for web. Did you find any solution to this?
