### ISSUE TITLE
Do I need to call `registerPlugin(FirebaseAnalytics.class);` in Capacitor V3 Version?

### ISSUE THREAD

**Issue by selected-pixel-jameson** [capacitor-community/firebase-analytics#113]
It seems like the call to register the plugin when using Capacitor V3 is missing from the documentation.

Maybe I'm wrong, but isn't this required in your MainActivity.java?

```
  public void onCreate(Bundle savedInstanceState) {
    setOrientation(this);
    super.onCreate(savedInstanceState);

    // Custom plugin registration
    registerPlugin(FirebaseAnalytics.class);
  }
```

**Comment by brownoxford** [comment]
Nope, this is no longer necessary. See https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading
