### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleUtilities/AppDelegateSwizzler"

### ISSUE THREAD

**Issue by xyboox** [capacitor-community/firebase-analytics#119]
**Describe the bug**

**To Reproduce**
Add the plugin to Ionic ios 

**Expected behavior**
Compile successfully.

**Screenshots**
<img width="985" alt="Screenshot 2022-05-17 at 17 09 52" src="https://user-images.githubusercontent.com/642584/168831700-382fc23f-8c0f-463b-989c-c776fa35d4c7.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1

**Additional context**
Ionic:

   Ionic CLI                     : 6.19.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.4.1

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.6.0) : 1.5.0

System:

   NodeJS : v14.19.2 (/opt/homebrew/Cellar/node@14/14.19.2/bin/node)
   npm    : 6.14.17
   OS     : macOS Monterey

POD FILE:

platform :ios, '12.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityBarcodeScanner', :path => '../../node_modules/@capacitor-community/barcode-scanner'
  pod 'CapacitorCommunityContacts', :path => '../../node_modules/@capacitor-community/contacts'
  pod 'CapacitorCommunityFirebaseAnalytics', :path => '../../node_modules/@capacitor-community/firebase-analytics'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CapacitorStorage', :path => '../../node_modules/@capacitor/storage'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsResources', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  pod 'Firebase/Messaging'
end

**Comment by mukul-myhq** [comment]
Hi Maintainers, getting exact same issue here as well, any updates on this?
@xyboox were you able to figure it out?
Thanks!

**Comment by xyboox** [comment]
@mukul-myhq nope!

**Comment by jcesarmobile** [comment]
This is a conflict with some Cordova plugin that downloads conflicting versions for firebase packages.
I've released version 4.0.0 of the plugin without a specific Firebase version, so might have fixed the issue.
But looks like the versions of the Cordova plugin are very old, so the plugin might not build with those old version.
Ideally the Cordova plugin should be updated to use newer firebase dependencies.
Give version 4.0.0 a try and if it doesn't work, create a new issue and provide a sample app where the issue can be reproduced.
