### ISSUE TITLE
Add web support

### ISSUE THREAD

**Issue by priyankpat** [capacitor-community/firebase-analytics#12]
**Is your feature request related to a problem? Please describe.**
Firebase Analytics web plugin not supported at the moment.

**Describe the solution you'd like**
Implement [Firebase Analytics for web](https://firebase.google.com/docs/analytics/get-started?platform=web).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rdlabo** [comment]
Sorry, I looked at master branch. And I checked your great work now!

**Comment by rdlabo** [comment]
My repository changed to be recommend this project:
https://github.com/rdlabo-team/capacitor-firebase-analytics

**Comment by priyankpat** [comment]
Thank you. @dwieeb can we add @rdlabo to contributions list for this repo?

Closing the issue.
