### ISSUE TITLE
Vulnerability Scan

### ISSUE THREAD

**Issue by SumitThakr** [capacitor-community/firebase-analytics#126]
**Describe the bug**
In vulnerability scan we are getting two vulnerability after adding firebase-analytics in the project-
-Unsecure cryptographic protocols.
-Weak Random Number Generator.

**Additional context**
This issue we getting because of library uuid old version which is installed indirectly.

**Comment by jcesarmobile** [comment]
the plugin itself does nothing related to cryptography nor random number generation, so the bugs must come from google analytics SDKs, you should report it to them.
I've updated the SDKs to latest versions available just in case, if the problem is still present, as I said, report it to google.
