### ISSUE TITLE
BUG: iOS build fails with Framework not found FirebaseCoreDiagnostics

### ISSUE THREAD

**Issue by qliqdev** [capacitor-community/firebase-analytics#147]
**Describe the bug**
https://github.com/capacitor-community/firebase-analytics/blob/0e30af2cc8d290eb019162a02e41eb32f7d020f1/ios/Podfile#L10-L13

`pod 'Firebase/Core'` has been removed from Podfile

but it is imported here

https://github.com/capacitor-community/firebase-analytics/blob/0e30af2cc8d290eb019162a02e41eb32f7d020f1/ios/Plugin/Plugin.swift#L3

**To Reproduce**
1. open project files

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/5783161/208320053-a05bb3ee-7969-4bd1-bd71-79f6357d2b30.png">

**Comment by jcesarmobile** [comment]
I can't reproduce, can you provide a sample app?
what's your CocoaPods version? `pod --version`

Firebase/Core is automatically installed by having Firebase/Analytics.
FirebaseCoreDiagnostics is a separate pod, not imported by the plugin.
