### ISSUE TITLE
 Error: "FirebaseAnalytics.getAppInstanceId()" is not implemented on android

### ISSUE THREAD

**Issue by MaYoRr** [capacitor-community/firebase-analytics#148]
**Describe the bug**
 Error: "FirebaseAnalytics.getAppInstanceId()" is not implemented on android

<img width="698" alt="image" src="https://user-images.githubusercontent.com/49597310/211192526-6119537a-e510-473f-a230-8629b9de265a.png">

<img width="615" alt="image" src="https://user-images.githubusercontent.com/49597310/211192541-7fe5a352-ad0c-4671-88c5-9bb492d1a3fc.png">

<img width="738" alt="image" src="https://user-images.githubusercontent.com/49597310/211192583-2a4244af-ca46-41ae-9f36-881f04b60d82.png">

Android Emulator - Pixel 6

This theme don't work - https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented

**Comment by jcesarmobile** [comment]
I can't reproduce, can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing since no sample app was provided.
