### ISSUE TITLE
ability to  configure GoogleServices-info.plist without xcode for cicd

### ISSUE THREAD

**Issue by szymon-mutuu** [capacitor-community/firebase-analytics#159]
**Is your feature request related to a problem? Please describe.**
we use fully automated cicd pipeline and no need so far to commit generated iOS project. To configure firebase `GoogleServices-info.plist` needs to be added to the project and currently all the docs suggesting to use Xcode but it is not possible in the cicd environment.

**Describe the solution you'd like**
Either update the doc where the `GoogleServices-info.plist` should be placed or possibly some tool/script to do any necessary updates to the project

**Describe alternatives you've considered**
Don't really see alternatives. Adding Xcode project to the repository is very bad idea as it is hard to control what actual change are committed after interactions within Xcode app. 

**Additional context**
I believe in the past there were solutions not requiring Xcode usage. Some people suggesting using just a script to determine right target location of the `GoogleServices-info.plist`

**Comment by jcesarmobile** [comment]
This is out of the scope of the plugin. 
You can use node scripts or probably https://trapeze.dev/
