### ISSUE TITLE
Capacitor 5

### ISSUE THREAD

**Issue by qliqdev** [capacitor-community/firebase-analytics#162]
[https://capacitorjs.com/docs/updating/plugins/5-0](https://capacitorjs.com/docs/updating/plugins/5-0)

**Comment by patrickjquinn** [comment]
Blocking upgrades to 5.0 just FYI.

**Comment by Mobiletainment** [comment]
I have tried it out using patch-package and can confirm that it works. 👏
Thank you for the update @qliqdev.

Hope it gets merged soon @mesur-io 🤞
