### ISSUE TITLE
No podspec found 

### ISSUE THREAD

**Issue by paul-austin** [capacitor-community/firebase-analytics#17]
I've installed the plugin, but when i sync the project i get the following error 

[error] Error running update: Analyzing dependencies
[!] No podspec found for `CapacitorCommunityFirebaseAnalytics` in `../../node_modules/@capacitor-community/firebase-analytics`

This is my podfile 

platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityFirebaseAnalytics', :path => '../../node_modules/@capacitor-community/firebase-analytics'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

**Comment by joseph-navant** [comment]
Hi @paul-austin! Probably you got this error after execute `npx cap sync` command:
> ✖ Updating iOS native dependencies with "pod install" (may take several minutes):
> ✖ update ios:
> [error] Error running update: Analyzing dependencies
> [!] No podspec found for `CapacitorCommunityFirebaseAnalytics` in `../../node_modules/@capacitor-community/firebase-analytics`

This is the workaround I applied:
1. copy this file https://github.com/capacitor-community/firebase-analytics/blob/master/CapacitorCommunityFirebaseAnalytics.podspec (as .podspec, not .txt) into your `app-folder/node_modules/@capacitor-community/firebase-analytics`
2. execute `npx cap sync` from `app-folder` or `pod install` from `app-folder/ios/App` command
3. `npx cap open ios`
4. Product > Clean Build Folder
5. Product > Run or Product > Build

**Comment by paul-austin** [comment]
perfect, thank you.

**Comment by priyankpat** [comment]
v0.2.0 now contain the correct podspec filename. Closing the issue.
