### ISSUE TITLE
com.google.firebase.iid.zzbg is referenced as an interface from `com.google.firebase.messaging.zzf`

### ISSUE THREAD

**Issue by joseph-navant** [capacitor-community/firebase-analytics#18]
**Describe the bug**
After migration from capacitor-analytics to capacitor-community/firebase-analytics I got an error during build process in Android Studio:
> Task :capacitor-cordova-android-plugins:assembleDebug
> Transform artifact firebase-messaging.aar (com.google.firebase:firebase-messaging:20.1.2) with DexingWithClasspathTransform
AGPBI: {"kind":"error","text":"Type com.google.firebase.iid.zzbg is referenced as an interface from `com.google.firebase.messaging.zzf`.","sources":[{}],"tool":"D8"}
> Type com.google.firebase.iid.zzbg is referenced as an interface from `com.google.firebase.messaging.zzf`.

**To Reproduce**
1. Migrate from capacitor-firebase to capacitor-community/firebase-analytics
2. ionic build --prod && npx cap sync
3. npx cap open android
4. Build > Clean Project
5. Build > Rebuild Project

**Expected behavior**
A successful build :)

**Screenshots**
<img width="1398" alt="Captura de pantalla 2020-07-01 a las 0 01 30" src="https://user-images.githubusercontent.com/10757091/86181310-1006eb00-bb2e-11ea-8534-b8a827830844.png">

**Comment by AndersonSingh** [comment]
Hello, 

I ran into the same issue today. I resolved it by updating firebaseMessagingVersion =  '20.1.6' in the variables.gradle file and then rebuilding the project. I hope this helps.

Regards

**Comment by joseph-navant** [comment]
Hello,

Yes! It is working flawlessly!

I have another doubt about variables.gradle
When should I update this versions? I had same versions as capacitor template

Thank you!
