### ISSUE TITLE
Using the latest version of the SDK for IOS

### ISSUE THREAD

**Issue by loic-parent** [capacitor-community/firebase-analytics#187]
**Is your feature request related to a problem? Please describe.**
Hello, I have a message in the panel of Firebase Analytics that inform me that I have to update the SDK version for IOS to use the version **10.24.0**.
I currently use the version 5.0.1. Is the new version of `capacitor-community/firebase-analytics` using this SDK version or newer ?

**Describe the solution you'd like**
Ideally add a version 5.0.2 and also for the new major version 6.0.1 with this new requirement.

_Thanks for your help,
Loïc_

**Comment by loic-parent** [comment]
Hello,

Could someone help me about it?

_Thanks,
Loïc_

**Comment by 53R910** [comment]
I am facing the same problem, does anyone have any suggestions?

**Comment by shiv19** [comment]
@loic-parent The plugin isn't pinning the version of FirebaseAnalytics pod
https://github.com/capacitor-community/firebase-analytics/blob/e5f0741897a47f15f03826d04069364bf090c9e9/ios/Podfile#L12

You can try running pod repo update, and update your Podfile.lock

**Comment by loic-parent** [comment]
Hi @shiv19,

Thank you for your reply!

I have this in Podfile:
```
platform :ios, '13.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # …
  pod 'CapacitorCommunityFirebaseAnalytics', :path => '../../node_modules/@capacitor-community/firebase-analytics'
  # …
end

target 'MyApp' do
  capacitor_pods
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
```

So I should have `pod 'FirebaseAnalytics'` in just after `capacitor_pods`. Is that right?
I will try to update the podfile and I will also upgrade to version 6.

_Thanks again,
Loïc_

**Comment by shiv19** [comment]
@loic-parent you don't need to modify the generated Podfile.
Just open a terminal in the /ios folder of your project and run `pod repo update`

**Comment by loic-parent** [comment]
Hello, @shiv19,

Sorry for my late reply and thank you for yours :)
I will try to update it next week.
