### ISSUE TITLE
enable(): Promise<void> Isn't a function

### ISSUE THREAD

**Issue by TravBradfield** [capacitor-community/firebase-analytics#2]
I've implemented the plugin as the docs suggest. Each of the methods work as you've said however the enable() method doesn't exist. 

When I call this method I get the following error: 

ERROR Error: Uncaught (in promise): TypeError: AnalyticsPlugin.enable is not a function
TypeError: AnalyticsPlugin.enable is not a function

My implementation: 

```
import { Analytics } from 'capacitor-analytics';
const analytics = new Analytics();

analytics.enable().then(() => { console.log('analytics.enable')});
```

**Comment by stewones** [comment]
hey @TravBradfield 
sorry for delay, if you set up a minimal repo reproduction I would be happy to check this issue out.

**Comment by micahgoodman** [comment]
I'm getting this error as well, although it only shows up on Android.

I believe it's caused by changes in the new version of ionic, capacitor, and/or ionic-native. I recently updated those packages, and this plugin worked fine before that.

**Comment by MeijerM1** [comment]
I'm getting the same issue with AndroidX and capacitor version 2.0.1

`Msg: ERROR Error: Uncaught (in promise): TypeError: O.enable is not a function
    TypeError: O.enable is not a function`

Edit: It looks like the methods are simply not implemented for Android. I openend a PR to fix this #9 .

**Comment by priyankpat** [comment]
The repository is now part of the Capacitor Community with a new namespace `@capacitor-community/firebase-analytics`. Please take a look at the [documentation](https://github.com/capacitor-community/firebase-analytics/blob/master/README.md) to get started.

**Comment by priyankpat** [comment]
This plugin is now part of the **@capacitor-community** organisation space. Please update to the new package namespace `@capacitor-community/firebase-analytics`. You can find additional details about this plugin and it's public api [here](https://github.com/capacitor-community/firebase-analytics/blob/master/README.md). Closing this issue. Feel free to reopen if there are any other issues.
