### ISSUE TITLE
Error: userId is missing when trying to setScreenName

### ISSUE THREAD

**Issue by sabahang** [capacitor-community/firebase-analytics#20]
**Describe the bug**
When trying to setScreenName with `FirebaseAnalytics.setScreenName({ name: page });` I get an error `Error while set screen to analytics! Error: userId is missing`

**To Reproduce**
1. Setup the plugin and call setScreenName
2. The event is not sent to Firebase Analytics due the mentioned error

**Expected behavior**
Error wouldn't be thrown

**Screenshots**
Add below

**Desktop (please complete the following information):**
 - OS: Android

** additional description
I even tried to setUserId (although according to Firebase docs shouldn't be needed) using the below but to no avail:
```
FirebaseAnalytics.setUserId({
  userId: "john_doe_123"
});
```

![image](https://user-images.githubusercontent.com/2657540/86360071-89abef80-bc7a-11ea-96c9-77bbcbda5574.png)
![image](https://user-images.githubusercontent.com/2657540/86360358-ec9d8680-bc7a-11ea-8bdf-9deb9f661d71.png)

**Comment by priyankpat** [comment]
This has been addressed by https://github.com/capacitor-community/firebase-analytics/pull/16.
