### ISSUE TITLE
Erro remoteConfig()

### ISSUE THREAD

**Issue by lucasnpinheiro** [capacitor-community/firebase-analytics#23]
I'm having a problem in version 0.2.0

an error in remoteConfig ()

ERROR in node_modules/@capacitor-community/firebase-analytics/dist/esm/web.d.ts: 90: 9 - error TS1086: An accessor cannot be declared in an ambient context.

90 get remoteConfig (): any;

Could you tell me how to solve this problem.

**Comment by ujeon** [comment]
I removed `get` in ` get remoteConfig (): any;` and it works. (but this a makeshift measure I think)

**Comment by iamfirdous** [comment]
> I removed `get` in ` get remoteConfig (): any;` and it works. (but this a makeshift measure I think)

That worked for me as well, but it's just a workaround. Waiting for this to be fixed.

**Comment by polsola** [comment]
Hello! Is there any update on this issue? As you all people say removing the `get` works and I see there is a [Pull Request](https://github.com/capacitor-community/firebase-analytics/pull/26) with the change made, does updating Typescript fixes the issue also?

**Comment by brownoxford** [comment]
This is the result of an unfortunate break in backwards compatibility in the Typescript project, and is now expected functionality. Updating typescript to v3.7 or later should fix this issue.

See [this comment](https://github.com/capacitor-community/firebase-analytics/pull/26#pullrequestreview-622380673) for more information on the underlying cause and possible short-term workaround.

**Comment by kiranraj1430** [comment]
Hi, I just facing this same issue right now:
Compiled with problems:X

ERROR in ./node_modules/@capacitor-firebase/remote-config/dist/esm/web.js 3:0-132

Module not found: Error: Can't resolve 'firebase/remote-config' in 'D:\node_modules\@capacitor-firebase\remote-config\dist\esm'

I am using latest version only! How to fix it? no docs are there still
