### ISSUE TITLE
Error running update: Analyzing dependencies

### ISSUE THREAD

**Issue by ujeon** [capacitor-community/firebase-analytics#24]
**Describe the bug**

I have tried to install v0.2.0, but it caused [this](https://github.com/capacitor-community/firebase-analytics/issues/23) issue.

So, I remove that version and reinstall v0.1.3.

but error occur while updating iOS native dependencies.

Below is error message when run `ionic cap sync`

✔ Updating iOS plugins in 5.20ms
  Found 1 Capacitor plugin for ios:
    @capacitor-community/firebase-analytics (0.1.3)
✖ Updating iOS native dependencies with "pod install" (may take several minutes):
✖ update ios:
[error] Error running update: Analyzing dependencies
[!] No podspec found for `CapacitorCommunityFirebaseAnalytics` in `../../node_modules/@capacitor-community/firebase-analytics`

**Comment by Darrow8** [comment]
I have this issue as well.

**Comment by abrad-smile** [comment]
I have this issue as well, is there any news about it please?

**Comment by brownoxford** [comment]
This appears to have been fixed with #17 and version 0.2.0. If you continue to run into #23 and are unable to update typescript, #17 contains a workaround for manually adding the podspec file.
