### ISSUE TITLE
Accuracy of Android Data

### ISSUE THREAD

**Issue by beckyhilton** [capacitor-community/firebase-analytics#25]
I'm not sure this is exactly a bug but I've been having trouble getting accurate data into firebase analytics for android. Sometimes its showing that a ton of people are using a version that has only been pushed to our internal testing.  And then today when I was using that same version I'm not seeing anything in firebase or google analytics.  Am I the only one experiencing this?

**Comment by beckyhilton** [comment]
If I'm running from the Android emulator I can see the information in firebase analytics but when I'm doing it from a phone its not showing up.   I'm also seeing a big spike right after I push it to google play and then it stops or it shows phones that I know don't have it.

**Comment by brownoxford** [comment]
I'm closing this old issue. If this is still something that you are working on, please open a new report with specific details on what is and isn't working.
