### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by michalsisak** [capacitor-community/firebase-analytics#27]
I am implementing firebase-analytics for mobile app and I am using angular. I am not sure if I am missing something but once I hover on some function I don't see any information in VS Code regarding its parameters and output.

Is the project missing types declaration? 

I am using TSlint if it helps.
Example of my implementation, hovering on **logEvent()** only shows _any_:
```
import { Plugins } from '@capacitor/core';
const { FirebaseAnalytics } = Plugins;

publishEvent(event: Event): void {
  FirebaseAnalytics.logEvent({ name: eventName, params: value });
}
```

**Comment by HeikoKanzler** [comment]
Same issue here, just started with the plugin and can't get any TypesScript support in VSCode.
Did you find a solution?

**Comment by michalsisak** [comment]
Nothing, this repo seems not being actively maintained.

**Comment by HeikoKanzler** [comment]
Yeah, I think so. The Crashalytics Repo seems also to be outdated. I am fine without code insight, but I am worried about the maintenance of the plugins.

**Comment by markxoe** [comment]
Same here, but with many community Plugins

Edit:
I know that generating a Plugin generates Types (definitions.(d.)ts) but VSCode seems to not recognise them as it is implemented with 
```
declare module '@capacitor/core' {
    interface PluginRegistry {
        ...
    }
}
```

Maybe this is the Problem that VSCode is not able to read those informarions

**Comment by gugahoi** [comment]
It's been a couple of months since the last comment. Has anyone found any kind of progress here? Any custom definitions being used in the wild?

**Comment by brownoxford** [comment]
![Screen Shot 2021-03-26 at 1 28 53 PM](https://user-images.githubusercontent.com/755209/112670511-6001ac80-8e37-11eb-8abf-6ec9628238b0.png)

This seems to be working since the 0.2.0 release, are you still having this problem?

**Comment by michalsisak** [comment]
I see this repo is starting to come alive. Many thanks @brownoxford for this!

Your comment made me try different builds and different aproaches. I was already on 0.2.0 release, I tried 0.2.1 but still no luck.

Then I tried changing way how the package is imported.

Importing this way worked:
```typescript
import { FirebaseAnalytics } from '@capacitor-community/firebase-analytics';
```

The problem occurs when we import package as recommended by [Capacitor docs](https://capacitorjs.com/docs/apis#api-usage):

> A common mistake is to import a plugin directly, then use the plugin API immediately, resulting in the web implementation being used:
By using the plugins from the plugin registry (Plugins object), the native implementation of the plugin is used (if available), with fallback to the web version.

```typescript
import { Plugins, Capacitor } from '@capacitor/core';
const { FirebaseAnalytics } = Plugins;
```

Not sure as to how manage getting code insight with this approach.

**Comment by brownoxford** [comment]
Hmm, here are my imports for the working capacitor v2 implementation where I got that screenshot:

```
import { Plugins } from "@capacitor/core";
import "@capacitor-community/firebase-analytics";

const { FirebaseAnalytics } = Plugins;
```

It looks like your first implementation may not have been working because you were not also importing "@capacitor-community/firebase-analytics" - you need that import because it actually exports all of the definitions for the plugin via `export * from './definitions'`

```
import { Plugins } from '@capacitor/core';
const { FirebaseAnalytics } = Plugins;
```

The new style you show is only for capacitor v3, so I would not use that unless you are upgrading:
```
# Capacitor V3 only
import { FirebaseAnalytics } from '@capacitor-community/firebase-analytics';
```

**Comment by brownoxford** [comment]
@michalsisak did the updated import fix the issue for you?

**Comment by michalsisak** [comment]
@brownoxford Importing `import "@capacitor-community/firebase-analytics";` solved the issue! Thank you. Will close the issue now.
