### ISSUE TITLE
Error on XCode build

### ISSUE THREAD

**Issue by madmacc** [capacitor-community/firebase-analytics#3]
I have followed the setup instructions I am getting the following error using XCode 11.3:

`type 'analytics' has no member 'setAnalyticsCollectionEnabled'`

It has the same error in the following places at line Analytics.setAnalyticsCollectionEnabled:
```
  @objc func enable(_ call: CAPPluginCall) {
    DispatchQueue.main.async {
      Analytics.setAnalyticsCollectionEnabled(true)
      call.success()
    }
  }
  
  @objc func disable(_ call: CAPPluginCall) {
    DispatchQueue.main.async {
      Analytics.setAnalyticsCollectionEnabled(false)
      call.success()
    }
  }
```

It is working fine on Android.
I have tried it with and without the 'enable' in the code.
```
enable() {
    return analytics.enable();
  }
```

```
Ionic:

   Ionic CLI                     : 5.4.5 (C:\Users\fullo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 6 other plugins)
```

**Comment by stewones** [comment]
hey @madmacc thats really weird. are you able to set up a repo for this?

**Comment by madmacc** [comment]
@stewwan Thanks for the reply.  I will see what I can do, its not my code so I will have to obtain permission.  I have managed to build your demo app https://github.com/stewwan/capacitor-analytics-demo without the error so I am just looking at what the differences are.

**Comment by madmacc** [comment]
I seem to have resolved this issue.  It seems I just needed to run ```sudo gem install cocoapods``` as per your instructions.  I was pretty sure I had already run this though.

**Comment by madmacc** [comment]
I seem to have resolved this issue.  I just needed to run sudo gem install cocoapods as per your instructions. I was pretty sure I had already run this though.
The repo I was making for you worked fine, so I figured I messed something up in the main project.

**Comment by stewones** [comment]
glad to hear @madmacc closing this issue for now, feel free to open another one if you feel in need.
