### ISSUE TITLE
[Question] Capacitor vs js

### ISSUE THREAD

**Issue by duy-a** [capacitor-community/firebase-analytics#4]
Hi, I am currently new to the ionic/ capacitor framework. Based on my understanding, the capacitor allows the access to the native capabilities, so as a newbie, I have a question:

What is the difference/ benefits using the capacitor vs web way (i.e angularfire in ionic angular) to enable the analytics? Does the capacitor plugin collect more information related to the device itself?

Thank you and looking forward for your response.

**Comment by kevinboosten** [comment]
Great question! I’ve once asked something similar in the capacitor slack group but did not got that much response:
https://getcapacitor.slack.com/archives/C88QP9W56/p1579510119015400

Not to hijack your thread, but here’s my question: 
> Question regarding Firebase Analytics. I see that @angular/fire now also supports analytics and remote config, and this just works like a charm. Including some nice provides that will hook into the angular router to determine page views and use the authenticated user to set the user id.  (ScreenTrackingService, UserTrackingService). https://github.com/angular/angularfire/issues/2178

> Because this is working great in an Ionic app with Capacitor, is there still any need to use a capacitor plugin that provides this functionality? (e.g. https://github.com/philmerrell/capacitor-firebase-analytics or https://github.com/stewwan/capacitor-analytics). What’s the benefit of using the “web” vs native implementation?

Couple of things I can imagine are:
- native analytics have better access to native views like modals/alert/push notifications that could be of any interest 
- web version has better integration in a angular setup (screentrackingservice)

**Comment by stewones** [comment]
as answered by @Boosten native analytics have better info despite the setup. it's worth it.
