### ISSUE TITLE
Firebase analytics is not initialized on iOS

### ISSUE THREAD

**Issue by SalahAdDin** [capacitor-community/firebase-analytics#42]
**Describe the bug**
Documentation states to use `initializeFirebase` only for web devices, but i'm getting an initilization problem in **iOs** too.

**To Reproduce**
1. Launch the application.
2. Go to Firebase Analytics debug mode, you won't see any new event incoming.
3. Go to the Safari's web inspector and open a debugger for the device.
4. Go to the console and see the error.

**Expected behavior**
As Android, it should be initialized itself without to do it manually in code.

**Screenshots**
![Captura de Pantalla 2020-12-09 a la(s) 14 12 51](https://user-images.githubusercontent.com/5034215/101623209-27c19400-3a29-11eb-9632-fd58db71ae5a.png)

**Desktop (please complete the following information):**
 - OS: Mac OsX 10.15.7
 - Browser Safari
 - Version 14.0.1 (15610.2.11.51.10, 15610)

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus

**Additional context**

**Comment by markxoe** [comment]
Do you have the Google services file for ios installed? It works on my project...

**Comment by SalahAdDin** [comment]
Yes, I have it.

**Comment by markxoe** [comment]
Could you post some code? That would be helpful to debug

**Comment by SalahAdDin** [comment]
This is the original initilization funtion:
```
async initAnalytics() {
    const deviceInfo = await Device.getInfo()
    if (deviceInfo.platform === "web") {
      FirebaseAnalytics.initializeFirebase(appEnv.firebaseConfig)
    }

    this.setProperty({
      name: "platform",
      value: deviceInfo.platform,
    })
    this.setProperty({
      name: "appVersion",
      value: deviceInfo.appVersion,
    })
    this.setProperty({
      name: "appBuild",
      value: deviceInfo.appBuild,
    })
    this.setProperty({
      name: "osVersion",
      value: deviceInfo.osVersion,
    })
  }
```

I added **ios** as platform to initialize too and i don't get the warning, but i don't get any log too.

I don't understand what is the problem.

Do i need the certification for Firabese as we need it for Cloud messages?

**Comment by markxoe** [comment]
Did you:
- Add the iOS App to Firebase in `Project settings` -> `My Apps`
- Sync the Capacitor Native Code with `npx cap sync ios`

**Comment by SalahAdDin** [comment]
Yeah, both of them we did.

I think i found the problem here: I didn't enabled the debug mode with the correct command. Now I did it and i can see analytics events in the console:
![Captura de Pantalla 2020-12-10 a la(s) 15 07 37](https://user-images.githubusercontent.com/5034215/101771025-5eb3aa80-3afa-11eb-9017-f0d019ba6ab7.png)

After testing it in the console, i will close this issue.

**Comment by cyril-colin** [comment]
Hi ! Can you tell me what you mean by " I didn't enabled the debug mode with the correct command" ? Because I have the same problem for my project :P 

Thank you !

**Comment by markxoe** [comment]
You have to do it like this: ~https://firebase.google.com/docs/analytics/debugview~ https://github.com/capacitor-community/firebase-analytics#enable-debug-view

**Comment by cyril-colin** [comment]
Thank you for your response.

In fact, my problem was that my Podfile wasn't up to date after my `npx cap sync` so I had to add this : 

```ruby
  pod 'CapacitorCommunityFirebaseAnalytics', :path => '../../node_modules/@capacitor-community/firebase-analytics'
```

**Comment by brownoxford** [comment]
Sounds like this issue has been resolved - if it is still a problem for you, please reopen.

**Comment by JohnGeorgiadis** [comment]
@cyril-colin  after more than a year I spent a day trying to figure this out. In the end I just needed to add the pod manually thanks!
