### ISSUE TITLE
Issue using xcode iPhone simulator with new M1 chipset

### ISSUE THREAD

**Issue by joshlit** [capacitor-community/firebase-analytics#44]
**Describe the bug**
Attempting to use iPhone simulator using xcode using an M1 Mac Mini gives the following error: 
`[PROJECTPATH]/ios/App/Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector(FIRAnalyticsConnector_a8eeba373b74508311b8b22b8d3202a6.o), building for iOS Simulator, but linking in object file built for iOS, file '[PROJECTPATH]/ios/App/Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector' for architecture arm64`

I have found this - https://github.com/firebase/firebase-ios-sdk/issues/6520 which may be of some help, but I'm not knowledgeable about any ios stuff at all

**Comment by markxoe** [comment]
I don't have any idea 😅 but maybe this helps: https://stackoverflow.com/questions/64171400/xcode-12-firanalyticsconnector-build-error/64183786#64183786

**Comment by joshlit** [comment]
> I don't have any idea 😅 but maybe this helps: https://stackoverflow.com/questions/64171400/xcode-12-firanalyticsconnector-build-error/64183786#64183786

sadly this brings other issues for me :( (css of the app doesn't load etc). I guess I'll have to wait for a fix

**Comment by brownoxford** [comment]
This is not an issue with capacitor-community/firebase-analytics, please see https://github.com/firebase/firebase-ios-sdk/issues/6520 for workarounds and discussion of fixes in later versions of FirebaseAnalytics for ios.
