### ISSUE TITLE
Still maintained??

### ISSUE THREAD

**Issue by selected-pixel-jameson** [capacitor-community/firebase-analytics#48]
Is this project still maintained? It looks like it’s been awhile since it’s been updated.

**Comment by aprat84** [comment]
@priyankpat Is anybody being able to maintain this project?

**Comment by markxoe** [comment]
Are there requirements to get a maintainer? 😅 (Just asking)

**Comment by brownoxford** [comment]
I am beginning to maintain the project. @markxoe if you are also interested, please see #52
