### ISSUE TITLE
Compile release mode

### ISSUE THREAD

**Issue by gusmarra** [capacitor-community/firebase-analytics#5]
Hi,

I was able to use the plugin but when I am trying to make a realease version I got a Gandle error and I am not able to do it. 

Do you have any way to avoid this?

Thanks

**Comment by stewones** [comment]
can you try again from 2.0.1 ?

**Comment by gusmarra** [comment]
Now it is not working at all. When you try to run it on a device you got the following error

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ------, PID: 12408
    java.lang.RuntimeException: Unable to start activity ComponentInfo{----/----.MainActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class androidx.coordinatorlayout.widget.CoordinatorLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)

**Comment by stewones** [comment]
Are you targeting android 29? Please give it a try with a clean install from capacitor v2

**Comment by gusmarra** [comment]
Capacitor V2 is still beta. Is there a way I can install again the previous version of the plugin?

**Comment by stewones** [comment]
Sure you can try removing node_modules, package.lock and npm install capacitor-analytics@0.0.4

Then npx cap sync android

**Comment by gusmarra** [comment]
Thanks. I was able to roll it back but I am getting the following error

 Uncaught (in promise): TypeError: Cannot read property 'logEvent' of undefined
    TypeError: Cannot read property 'logEvent' of undefined

After the update this code was working.

Just using

import { Analytics } from 'capacitor-analytics';
const analytics = new Analytics();

ngOnInit() {
         analytics.logEvent({
        name: 'view',
        params: { page: 'carrito' }
      });
  }

Also try placing the code on the constructor.

Thanks

**Comment by stewones** [comment]
sounds like js api is broken.

you can try using capacitor api directly

```ts
import { Plugins } from '@capacitor/core';
const { AnalyticsPlugin } = Plugins;

//...

AnalyticsPlugin.logEvent(...)
```

also don't forget to initialise the plugin in java code as described on readme
`add(AnalyticsPlugin.class);`

**Comment by gusmarra** [comment]
Still the same. I have init the plugin

import io.stewan.capacitor.analytics.AnalyticsPlugin;
//...

add(AnalyticsPlugin.class);

**Comment by gusmarra** [comment]
Hi stewwan, I found the issue. It is running again. 
Thanks

**Comment by stewones** [comment]
nice @gusmarra. feel free to report any new issue.
