### ISSUE TITLE
Analytics.setScreenName failing my iOS build on latest macOS build in Azure

### ISSUE THREAD

**Issue by karm435** [capacitor-community/firebase-analytics#68]
We are using the latest 0.2.2 release of the plugin. 

However, today macOS builds are updated on Azure and suddenly the warning of Analytics.setScreenName is now an error and we cannot build the project.

Is there any way to resolve this?

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/6672354/117926733-90949b80-b33c-11eb-9cc5-732ca05086bf.png">

**Comment by karm435** [comment]
I see that change is already made on 8th of Apr, Is there any plan for releasing the fix?

**Comment by slajar** [comment]
We encounter this issue now as well. Please fix it asap. Thanks in advance

**Comment by slajar** [comment]
@karm435 where did you see the change?

**Comment by karm435** [comment]
If you check the repo git history you can see check in there after the release of 0.2.2.

**Comment by slajar** [comment]
Ahh, right. So, it "just" must be released through npm

**Comment by karm435** [comment]
Yes, they need to do another release. We copied the plugin locally and using that until we get the new release.

**Comment by brownoxford** [comment]
I've just release v0.2.3 with the fix for #64, please let me know if it resolves this issue for you.

**Comment by mRoca** [comment]
Thanks @brownoxford ! But caution with the 0.2.3 version: I'm not sure it's working for android (see https://github.com/capacitor-community/firebase-analytics/pull/64/files#r631191882 )

**Comment by slajar** [comment]
On iOS it is working. 👍

**Comment by karm435** [comment]
> Thanks @brownoxford ! But caution with the 0.2.3 version: I'm not sure it's working for android (see https://github.com/capacitor-community/firebase-analytics/pull/64/files#r631191882 )

But it is change for only iOS how does it impact the Android version?

**Comment by karm435** [comment]
> I've just release v0.2.3 with the fix for #64, please let me know if it resolves this issue for you.

It broke the Android build

![image](https://user-images.githubusercontent.com/6672354/118057424-4e686a00-b3cf-11eb-9e78-23ab3a161b31.png)

**Comment by karm435** [comment]
> > Thanks @brownoxford ! But caution with the 0.2.3 version: I'm not sure it's working for android (see https://github.com/capacitor-community/firebase-analytics/pull/64/files#r631191882 )
> 
> But it is change for only iOS how does it impact the Android version?

I spoke too soon

**Comment by anggariskyraharja** [comment]
> > I've just release v0.2.3 with the fix for #64, please let me know if it resolves this issue for you.
> 
> It broke the Android build
> 
> ![image](https://user-images.githubusercontent.com/6672354/118057424-4e686a00-b3cf-11eb-9e78-23ab3a161b31.png)

Is there any way to fix the Android build?

**Comment by karm435** [comment]
As interim solution we have downloaded the code at 0.2.2 and had made the change locally for iOS and using the plugin as local plugin.

**Comment by anggariskyraharja** [comment]
> As interim solution we have downloaded the code at 0.2.2 and had made the change locally for iOS and using the plugin as local plugin.

Thank you very much for your solution

**Comment by brownoxford** [comment]
I've release 0.3.0 with minimum Android unit testing and a fix for the broken Android build. This release also updates the google analytics package to latest (19.0.0), please let me know if it solves the issues for you.

@all-contributors please add @karm435 for bug

**Comment by brownoxford** [comment]
@all-contributors please add @mRoca for bug

**Comment by karm435** [comment]
> I've release 0.3.0 with minimum Android unit testing and a fix for the broken Android build. This release also updates the google analytics package to latest (19.0.0), please let me know if it solves the issues for you.
> 
> 
> 
> @all-contributors please add @karm435 for bug

Thank you so much, I will test it later today and will update you.

**Comment by karm435** [comment]
Build are successful now. Thanks
