### ISSUE TITLE
Capacitor 2.0 support

### ISSUE THREAD

**Issue by sagits** [capacitor-community/firebase-analytics#7]
Hi, looks like my project was unable to import the plugin:

 `Cannot read property 'enable' of undefined`

I'm currently using capacitor 2.0beta (because I want to use androidx support). Maybe that's the problem? Thanks in advance.

**Comment by sagits** [comment]
My bad, it works with capacitor2.0, but im unable to run the enable() method of the plugin. It looks like it won't exist in the plugin. Any advice? Thanks in advance.

![image](https://user-images.githubusercontent.com/6174566/78382013-89815280-75ac-11ea-86f2-2d02f5216473.png)

**Comment by priyankpat** [comment]
This is now addressed with @capacitor-community/firebase-analytics package. Closing the issue.
