### ISSUE TITLE
Unable to archive with Bitcode enabled 

### ISSUE THREAD

**Issue by SrinivasanTarget** [capacitor-community/firebase-analytics#71]
**Describe the bug**

- Xcode version: 11.4.1
- Firebase SDK version: 7.11.0
- Firebase Component: Analytics

Couldn't build apps with Bitcode enabled. Below is the error I'm getting while building the app for iPad devices, 

```

▸ Compiling CapacitorCommunityFirebaseAnalytics_vers.c
▸ Compiling Plugin.m
▸ Compiling CapacitorCommunityFirebaseAnalytics-dummy.m
▸ Touching CapacitorCommunityFirebaseAnalytics.framework (in target 'CapacitorCommunityFirebaseAnalytics' from project 'Pods')
▸ Copying Pods-App-umbrella.h
▸ Processing Pods-App-Info.plist
▸ Compiling Pods-App-dummy.m
▸ Compiling Pods_App_vers.c
▸ Touching Pods_App.framework (in target 'Pods-App' from project 'Pods')
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Compiling AppDelegate.swift
▸ Linking App

❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1200.0.32.2.0_0' Reader: '1103.0.32.59_0')', using libLTO version 'LLVM version 11.0.3, (clang-1103.0.32.59)' for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/sekars/Library/Developer/Xcode/DerivedData/App-buqylyqebjbcffaltpbqiokfcssp/Build/Intermediates.noindex/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/App.app/App normal arm64
(1 failure)
[15:39:40]: Exit status: 65

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.181.0                 |
| sdk         | iPhoneOS13.4.sdk        |
+-------------+-------------------------+
```

The above issue is reproducible in multiple code versions I have tried. Everything goes smooth when the Bitcode is disabled. Any thoughts on this? I'm using the latest version of `CapacitorCommunity/FirebaseAnalytics`. Let me know if you need more details from my side.

**Comment by SrinivasanTarget** [comment]
@brownoxford Can you please help me on this?

**Comment by brownoxford** [comment]
What version of capacitor are you using? If you are on v3, can you please try this with XCode 12 or greater? If you are using capacitor v2, please make sure you are installing v0.3.2 of the @capacitor-community/firebase-analytics plugin.

**Comment by jcesarmobile** [comment]
closing since there was no response
if somebody still faces this issue, please, create a new issue and provide a sample app where the issue can be reproduced

**Comment by kixes** [comment]
Re-opening. This is an issue on xcode 13 as well.
