### ISSUE TITLE
Version 0.3.0 has dependency of Capacitor 3

### ISSUE THREAD

**Issue by salohcin714** [capacitor-community/firebase-analytics#72]
**Describe the bug**
`firebase-analytics@0.3.0` has dependency `@capacitor/core@^3.0.0`. Capacitor 3 support looks to be in beta and has not yet been officially released. Plugins behave differently in Capacitor 3 and this is causing the plugin to no longer function with Capacitor 2 projects.

This is causing the following error:

```
Error: node_modules/@capacitor-community/firebase-analytics/node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
  Types of property 'Plugins' are incompatible.
    Property 'FirebaseAnalytics' is missing in type '{ [pluginName: string]: { [prop: string]: any; }; }' but required in type 'PluginRegistry'.

16 export interface CapacitorInstance extends CapacitorGlobal {
                    ~~~~~~~~~~~~~~~~~

  node_modules/@capacitor-community/firebase-analytics/dist/esm/definitions.d.ts:3:9
    3         FirebaseAnalytics: FirebaseAnalyticsPlugin;
              ~~~~~~~~~~~~~~~~~
    'FirebaseAnalytics' is declared here.
```

**To Reproduce**
Run production build on Angular project using `@capacitor/core@^2.4.7` and `firebase-analytics@0.3.0`.

**Expected behavior**
Type definitions to work properly with Capacitor 2 until support for Capacitor 3 is officially released

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS

**Smartphone (please complete the following information):**

**Additional context**

Angular: 11.0.2

**Comment by salohcin714** [comment]
After further investigation, it looks like the dependency is actually `@capacitor/core@latest` which is now Capacitor 3 since it is now out of beta

**Comment by tobium** [comment]
So could you please change the dependency to @capacitor/core@2.4.7 ?

**Comment by tobium** [comment]
I created a pull request for a quick fix: https://github.com/capacitor-community/firebase-analytics/pull/74

**Comment by vanessag** [comment]
Please fix! This plugin is currently breaking the build with both capacitor 2.4.7 and 3.0.

**Comment by tobium** [comment]
I need someone who approves my "fix"

**Comment by brownoxford** [comment]
I've just rolled out version 0.3.1 to npm with the merged PR, thanks everyone!

@all-contributors please add @tobium for code

**Comment by brownoxford** [comment]
@all-contributors please add @slajar for review

**Comment by brownoxford** [comment]
@all-contributors please add @salohcin714 for bug

**Comment by brownoxford** [comment]
@tobium, @vanessag, @salohcin714 Please let me know whether this issue is resolved for you.

**Comment by vanessag** [comment]
@brownoxford I think I am having a different issue than the one in the original bug report. I am getting an error when building with Xcode:

`/myApp/ios/App/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m:36:9: 'GoogleUtilities/GULURLSessionDataResponse.h' file not found`

I will open a new issue.

**Comment by brownoxford** [comment]
Closing this issue out with the release of `v0.3.2`, please open another issue if new problems arise.
