### ISSUE TITLE
Error: Cannot find symbol this.init(savedInstanceState, plugins, null);

### ISSUE THREAD

**Issue by vimalkumar015** [capacitor-community/firebase-analytics#94]
I followed Same as the Document, in web everything is fine.
But in Android while Build the project android studios throws this error.

ScreenShot of MainActivity.java
<img width="864" alt="Screenshot 2021-06-03 at 5 04 43 PM" src="https://user-images.githubusercontent.com/19769860/120640478-292bc080-c490-11eb-93ee-536820bac4f2.png">

ScreenShot of Error
<img width="1294" alt="Screenshot 2021-06-03 at 5 05 30 PM" src="https://user-images.githubusercontent.com/19769860/120640571-43fe3500-c490-11eb-845b-6c369c25e887.png">

ScreenShot of Error location at BridgActivity.java
<img width="1101" alt="Screenshot 2021-06-03 at 5 05 42 PM" src="https://user-images.githubusercontent.com/19769860/120640756-7740c400-c490-11eb-9cb5-5bf5916a7d27.png">

Ionic Info
<img width="435" alt="Screenshot 2021-06-03 at 5 06 18 PM" src="https://user-images.githubusercontent.com/19769860/120640792-81fb5900-c490-11eb-9d00-6ba41222e7cc.png">

<img width="484" alt="Screenshot 2021-06-03 at 5 18 50 PM" src="https://user-images.githubusercontent.com/19769860/120640847-93dcfc00-c490-11eb-8410-8dd56881ada3.png">

Please Help me as soon as possible.

**Comment by brownoxford** [comment]
@vimalkumar015 You can remove the entire onCreate method as documented here: https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading

I will keep this bug open to ensure that I modify the install documentation here.

**Comment by vimalkumar015** [comment]
Thanks for the Help.

**Comment by brownoxford** [comment]
Need to update documentation to reflect the new method of automatically loading plugins in Android.

**Comment by crebuh** [comment]
Yes this works, trapped into the same problem yesterday.

```
package com.my.app; // replace with your bundle id

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
//import com.getcapacitor.Plugin;
import com.getcapacitor.community.firebaseanalytics.FirebaseAnalytics;

//import java.util.ArrayList;

public class MainActivity extends BridgeActivity {

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    registerPlugin(FirebaseAnalytics.class);

    // Initializes the Bridge
//     this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
//             // Additional plugins you've installed go here
//             // Ex: add(TotallyAwesomePlugin.class);
//             add(FirebaseAnalytics.class);
//           }});
  }
}
```

just use  registerPlugin(FirebaseAnalytics.class); instead of the init method. all other plugins (which are now part of the core of capacitor) are then still register automatically

**Comment by santekotturi** [comment]
@brownoxford what's the final result of this? 

Should the docs be:
```
package com.communitas.MyAppName;
import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.community.firebaseanalytics.FirebaseAnalytics;

public class MainActivity extends BridgeActivity {

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    registerPlugin(FirebaseAnalytics.class);

  }
}

```

**Comment by brownoxford** [comment]
Updated docs - because of the Capacitor 3's [automatic Android plugin loading](https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading), you no longer need to edit `MainActivity.java` when adding or removing files via NPM.
> In Capacitor 3, it is preferred to automatically load the Android plugins. In MainActivity.java, the onCreate method can be removed. You no longer have to edit this file when adding or removing plugins installed via npm.
